name: Alerta Youtube 5min

on:
  schedule:
    - cron: '*/5 * * * *' # Comando para rodar a cada 5 minutos
  workflow_dispatch: # Isso cria o botão para você testar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permite que o robô salve o arquivo de memória
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Bibliotecas
        run: pip install feedparser requests

      - name: Rodar Script
        run: python alerta_youtube.py

      - name: Salvar Memória
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ultimo_video.txt || exit 0
          git commit -m "Atualiza ultimo_video.txt" || exit 0
          git push
